/*
 * This source file was generated by the Gradle 'init' task
 */
package agent;

import java.util.UUID;

import agent.GeneticAlgorithm.AgentIndividual;
import agent.GeneticAlgorithm.AgentWatcher;
import jade.core.Profile;
import jade.core.ProfileImpl;
import jade.core.Runtime;
import jade.wrapper.AgentContainer;
import jade.wrapper.AgentController;
import jade.wrapper.ContainerController;
import jade.wrapper.StaleProxyException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws StaleProxyException {

        Runtime rt = Runtime.instance();
        Profile p = new ProfileImpl();

        p.setParameter(Profile.GUI, "true");

        AgentContainer main = rt.createMainContainer(p);

        Profile pop1p = new ProfileImpl();
        pop1p.setParameter(Profile.CONTAINER_NAME, "pop1");

        Profile pop2p = new ProfileImpl();
        pop2p.setParameter(Profile.CONTAINER_NAME, "pop2");

        ContainerController pop1 = rt.createAgentContainer(pop1p);

        ContainerController pop2 = rt.createAgentContainer(pop2p);

        AgentController watcher = main.createNewAgent("watcher", AgentWatcher.class.getName(), new Object[]{"pop1", "pop2"});
    
        watcher.start();


        for (int i = 0; i < 25; i++) {
            pop1.createNewAgent(
                    "ind-" + UUID.randomUUID(),
                    AgentIndividual.class.getName(),
                    null).start();
        }

        for (int i = 0; i < 25; i++) {
            pop2.createNewAgent(
                    "ind-" + UUID.randomUUID(),
                    AgentIndividual.class.getName(),
                    null
            ).start();
        }
    }
}