/*
 * This source file was generated by the Gradle 'init' task
 */
package agent;

import agent.fifth.AgentCalculator.AgentCalculator;
import agent.fifth.AgentClient.AgentClient;
import agent.fifth.AgentCoordinator.AgentCoordinator;
import jade.core.Profile;
import jade.core.ProfileImpl;
import jade.core.Runtime;
import jade.wrapper.AgentContainer;
import jade.wrapper.AgentController;
import jade.wrapper.StaleProxyException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws StaleProxyException {

        Runtime rt = Runtime.instance();
        Profile p = new ProfileImpl();

        p.setParameter(Profile.GUI, "true");

        AgentContainer mainContainer = rt.createMainContainer(p);

        AgentController client = mainContainer.createNewAgent("client", AgentClient.class.getName(), null);

        client.start();

        for (int i = 1; i <= 3; i++) {
            mainContainer
                    .createNewAgent("coordinator" + i,AgentCoordinator.class.getName(), null)
                    .start();
        }

        for (int i = 1; i <= 3; i++) {
            mainContainer
                    .createNewAgent("calculator" + i, AgentCalculator.class.getName(), null)
                    .start();
        }
    }
}